name: test-workflow
on: [push]
jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
            - name: Build
              run: |
                  npm install -g yarn
                  yarn
                  yarn build
            - name: Deploy
              uses: crazy-max/ghaction-github-pages@v2
              with:
                  build_dir: dist
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
